/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Submission = IDL.Record({
  'couponCode' : IDL.Text,
  'rewardAmount' : IDL.Nat,
  'city' : IDL.Text,
  'feedback' : IDL.Text,
  'state' : IDL.Text,
  'timestamp' : IDL.Int,
  'upiId' : IDL.Text,
});

export const idlService = IDL.Service({
  'filterByState' : IDL.Func([IDL.Text], [IDL.Vec(Submission)], ['query']),
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'getRewardStats' : IDL.Func([], [IDL.Nat, IDL.Vec(IDL.Nat)], ['query']),
  'getSubmission' : IDL.Func([IDL.Text], [IDL.Opt(Submission)], ['query']),
  'searchByCouponPrefix' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Submission)],
      ['query'],
    ),
  'submitClaim' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateRewardAmount' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Submission = IDL.Record({
    'couponCode' : IDL.Text,
    'rewardAmount' : IDL.Nat,
    'city' : IDL.Text,
    'feedback' : IDL.Text,
    'state' : IDL.Text,
    'timestamp' : IDL.Int,
    'upiId' : IDL.Text,
  });
  
  return IDL.Service({
    'filterByState' : IDL.Func([IDL.Text], [IDL.Vec(Submission)], ['query']),
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'getRewardStats' : IDL.Func([], [IDL.Nat, IDL.Vec(IDL.Nat)], ['query']),
    'getSubmission' : IDL.Func([IDL.Text], [IDL.Opt(Submission)], ['query']),
    'searchByCouponPrefix' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Submission)],
        ['query'],
      ),
    'submitClaim' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateRewardAmount' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };