/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Submission = IDL.Record({
  'status' : IDL.Text,
  'couponCode' : IDL.Text,
  'rewardAmount' : IDL.Nat,
  'city' : IDL.Text,
  'feedback' : IDL.Text,
  'state' : IDL.Text,
  'timestamp' : IDL.Int,
  'upiId' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'filterByState' : IDL.Func([IDL.Text], [IDL.Vec(Submission)], ['query']),
  'getActiveSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getRewardStats' : IDL.Func([], [IDL.Nat, IDL.Vec(IDL.Nat)], ['query']),
  'getSubmissionByCode' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(Submission)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAsRedeemed' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchByCouponPrefix' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Submission)],
      ['query'],
    ),
  'submitClaim' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateRewardAmount' : IDL.Func([IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Submission = IDL.Record({
    'status' : IDL.Text,
    'couponCode' : IDL.Text,
    'rewardAmount' : IDL.Nat,
    'city' : IDL.Text,
    'feedback' : IDL.Text,
    'state' : IDL.Text,
    'timestamp' : IDL.Int,
    'upiId' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'filterByState' : IDL.Func([IDL.Text], [IDL.Vec(Submission)], ['query']),
    'getActiveSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getRewardStats' : IDL.Func([], [IDL.Nat, IDL.Vec(IDL.Nat)], ['query']),
    'getSubmissionByCode' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Submission)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAsRedeemed' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchByCouponPrefix' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Submission)],
        ['query'],
      ),
    'submitClaim' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateRewardAmount' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };